package constants

import "github.com/svetozar12/dragon-cli/installers"

var CommonDevFe = []string{
	installers.NX_CYPRESS,
	installers.NX_ESBUILD,
	installers.NX_ESLINT_PLUGIN,
	installers.NX_JEST,
	installers.NX_LINTER,
	installers.NX_NODE,
	installers.NX_REACT,
	installers.NX_VITE,
	installers.NX_WORKSPACE,
	installers.SWC_CLI,
	installers.SWC_CORE,
	installers.TYPES_EXPRESS,
	installers.TYPES_JEST,
	installers.TYPES_NODE,
	installers.TYPES_REACT,
	installers.TYPES_REACT_DOM,
	installers.TSC_ESLINT_ESLINT_PLUGIN,
	installers.TSC_ESLINT_PARSER,
	installers.VITEST_PLUGIN_REACT,
	installers.VITEST_COVERAGE,
	installers.VITEST_UI,
	installers.CYPRESS,
	installers.ESLINT,
	installers.ESLINT_CONFIG_PRETTIER,
	installers.ESLINT_PLUGIN_CYPRESS,
	installers.ESLINT_PLUGIN_IMPORT,
	installers.ESLINT_PLUGIN_JSX_A11Y,
	installers.ESLINT_PLUGIN_REACT,
	installers.ESLINT_PLUGIN_REACT_HOOKS,
	installers.JEST,
	installers.JEST_ENV_NODE,
	installers.JSDOM,
	installers.TS_JEST,
	installers.TS_NODE,
	installers.VITE,
	installers.VITEST,
}
