name: CLI Test

on:
  push: # Trigger on any push event
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }} # Use the GITHUB_REF environment variable
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Download Go module dependencies
        run: go mod download

      - name: Build CLI tool
        run: go build -o dragon-cli

      - name: Run tests
        run: go test ./...

      - name: Install CLI tool
        run: sudo mv dragon-cli /usr/local/bin/dragon-cli
        # This step installs your CLI tool globally for testing purposes

      - name: Verify CLI tool
        run: dragon-cli --projectName=my-example-app --beFramework=nodejs --feFramework=Nextjs --installDeps=true
