# This workflow will run on push to the master branch and pull requests to master.

name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.20"

      - name: Download Go module dependencies
        run: |
          cd cli
          go mod download
        working-directory: ./ # Set the working directory to the root of your repository

      - name: Build CLI tool
        run: |
          cd cli
          go build -o dragon-cli
        working-directory: ./ # Set the working directory to the root of your repository

      - name: Run tests
        run: |
          cd cli
          go test -cover ./...
        working-directory: ./ # Set the working directory to the root of your repository
